# Generated by Django 4.2.20 on 2025-03-28 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('jigger', models.CharField(choices=[('S', 'Single'), ('D', 'Double')], default='S', max_length=1)),
                ('cocktail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cocktail')),
            ],
        ),
    ]
