# Generated by Django 4.2.20 on 2025-03-28 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_serving'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='glassware',
            field=models.CharField(choices=[('C', 'Collins'), ('H', 'Highball'), ('M', 'Martini'), ('R', 'Rocks'), ('S', 'Shot'), ('U', 'Coupe'), ('W', 'Wine')], default='H', max_length=1),
        ),
    ]
