# Generated by Django 4.2.20 on 2025-03-28 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_cocktail_glassware'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='serving',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='serving',
            name='date',
            field=models.DateField(verbose_name='Serving Date'),
        ),
    ]
