# Generated by Django 4.2.20 on 2025-03-28 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_ingredient_alter_serving_options_alter_serving_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='categorization',
            field=models.CharField(choices=[('A', 'Base Alcohol'), ('L', 'Liqueurs and Secondary Spirits'), ('M', 'Mixers'), ('G', 'Garnishes'), ('I', 'Ice'), ('F', 'Additional Flavorings')], default='A', max_length=1),
        ),
    ]
