# Generated by Django 4.2.20 on 2025-03-29 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_ingredient_categorization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='categorization',
            field=models.CharField(choices=[('A', 'Alcohol'), ('L', 'Liqueur'), ('M', 'Mixer'), ('G', 'Garnish'), ('I', 'Ice'), ('F', 'Flavoring')], default='A', max_length=1),
        ),
    ]
